"" set the color scheme
colorscheme ron
syntax on

""" set font
set guifont=Menlo:h11

"" set some editor defaults 
set number
set tabstop=4
set expandtab
set ruler
set nowrap

"" make markup languages a shiftwidth of 2
au Filetype htmldjango,html,coffee,ruby,css,less setlocal sw=2 sts=2 ts=2 textwidth=0

"" my fix for the django-templates bundle
au BufNewFile,BufRead *.djt set ft=htmldjango
